### ISSUE TITLE
move pins to a conda_build_config.yaml

### ISSUE THREAD

**Issue by beckermr** [conda-forge/rubinenv-feedstock#64]
Right now there are two overall issues with the way stack pins are done.

1. The pins need to be in a conda_build_config.yaml. This will make them easier to manage and compare to the main conda-forge pinnings. It will also make the ABI pinning of downstream repos in conda-forge easier. We can copy this file around. 

2. Some of the major pings being used do not reflect the declared ABI compatibility ranges that conda-forge uses. This is an actual bug that could cause seg faults or worse, silent errors, in actual builds of the stack. 

The solution to both is to move the pins to a conda_build_config.yaml and then use jinja2 to put them in the runtime env.

**Comment by ktlim** [comment]
As I understand it, for point 2 we should _not_ list our existing pins in our `conda_build_config.yaml` but instead use jinja2 variables (that are automatically available?) from `conda-forge-pinning`.

This would appear to bump us from mpich 3 to 4, and we would still need to specify our needed numpy 1.20 explicitly.  Is that correct?

**Comment by beckermr** [comment]
The jinja2 variables come from a combination of the local conda_build_config.yaml and the global pinnings. The local one overrides the global one, so you would get only local values.

Thus you would not have to worry about version bumps or extra specifications. 

You'd specify everything in the conda_build_config.yaml and that'd be the only spot.

**Comment by beckermr** [comment]
Also mpich 3 is ABI compatible with mpich 4.

**Comment by beckermr** [comment]
One other thing is for the recipe to use host sections properly to generate ABI range pins. The structure should be roughly (picking on mpich here)

```
host:
 - mpich
run:
 - blah blah # everything but mpich
```

Then in the conda_build_config.yaml, we list the exact pin of the smallest acceptable version (e.g., 3.1.2 for mpich).

**Comment by beckermr** [comment]
You could also just list 3 for mpich in the example and conda should pick the latest.
